# -*- coding: utf-8 -*-
"""hangman game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4xJgRNhu0CcyL9TcDM6dXy4125_oMHd
"""

import random

words = ["python", "programming", "computer", "hangman", "school", "game"]

word = random.choice(words)
guessed_letters = []
attempts = 6

print("🎮 Welcome to Hangman Game 🎮")
print("_ " * len(word))

# Game loop
while attempts > 0:
    guess = input("\nGuess a letter: ").lower()

    if guess in guessed_letters:
        print("⚠️ You already guessed that letter!")
        continue

    guessed_letters.append(guess)

    if guess in word:
        print("✅ Good job! Letter found.")
    else:
        attempts -= 1
        print(f"❌ Wrong guess! Attempts left: {attempts}")

    display_word = ""
    for letter in word:
        if letter in guessed_letters:
            display_word += letter + " "
        else:
            display_word += "_ "
    print(display_word)

    if "_" not in display_word:
        print("\n🎉 Congratulations! You guessed the word:", word)
        break

if attempts == 0:
    print("\n💀 Game Over! The word was:", word)
\